version: 0.2
env:
  variables:
    APP_NAME: "apiplayground"
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo install process started
      - npm install && npm install -g @angular/cli
  build:
    commands:
      - echo build process started now
      - cd $CODEBUILD_SRC_DIR/APIPlayground
      - ng build --configuration=production
  post_build:
    commands:
      - echo build process finished, we should upload to S3 now
      - cd $CODEBUILD_SRC_DIR/APIPlayground
      - cd dist/$APP_NAME
      - ls -la
      - aws s3 sync . s3://atjoseph/apiplayground/ --delete